# Generated by Django 5.1.3 on 2025-02-14 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"verbose_name": "Заявки", "verbose_name_plural": "Заявки"},
        ),
        migrations.CreateModel(
            name="TicketAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="tickets/attachments/", verbose_name="Фото"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("BEFORE", 'Фото "до"'), ("AFTER", 'Фото "после"')],
                        max_length=6,
                        verbose_name="Тип фото",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото заявки",
                "verbose_name_plural": "Фото заявок",
            },
        ),
    ]
